### ISSUE TITLE
How do I make use of esengine + application factory + sqlalchemy?

### ISSUE THREAD

**Issue by rlam3** [seek-ai/esengine#27]
How do I make use of esengine and have it play nice with in an application factory and sqlalchemy ORM?

I know I can make a flask plugin/extension for this but, how should I be mapping my sqlalchemy models over to esengine? I know the fields I want to index, it is just a matter of how you guys would recommending doing this? elasticsearch_dsl has a similar way of ODM. 

Do you guys have documentation or a simple example ? Thanks!

**Comment by rochacbruno** [comment]
Hi @rlam3 

IMO:

Should be nice to have a way to map ORM -> ODM, let's say, mapping SQLAlchemy, MongoEngine, pyDAL and others to ``esengine.Document``

But, I think EsEngine should be agnostic about that, so I think we are not going to include built-ins for that.

The way to go should be extensions, I did not played with this yet, But I have interest specially in doing something for MOngoEngine (should have a similar case to SQlAlchemy).

I wonder a thing working like that.

> lets say someone create a **esengine_ORM** module

```python
...
from esengine_mongoengine import MongoConnector
from myapp.mongo_models import Person

class PersonIndexer(MongoConnector) :
    index_model = Document  # allowing to override if customized
    base_model = Person  # here we pass the ORM doc class 
    index = "myindex"
    doctype = "person"
    _es = Elasticsearch(....)
    field_mapping = {
        # mongo_field : index_field
        "name": "name",
        "other": lambda x: do_domething # point to callable just like in Django.Haystack
    }

    def index(self, ):
        # this method can be override to allow custom queries
```

With the above we should have a **Connector** and we can run, maybe in a cron job or **signal** system (e.g: beaker, queue)

```bash
$ python -m esengine_mongoengine -c myfile.py 
```

The above should instantiate connector, execute query, index the documents.

A lot to be done here, but it is definitely  a **must have**, however we should take care of doing this separately keeping esengine small and ORm agnostic.

If you want to help on this take a look on how **django.haystack** works, a good example to follow.

@ederfmartins @andryw @emanuelvianna @tiagorm what do you guys think about it?

**Comment by ederfmartins** [comment]
Hi @rlam3, @rochacbruno

IMO:

I do not know if esengine should automatically communicate with an ORM made for SQL databases. With another nosql? Maybe.

I think particurlarly it may not be a good idea. While it is possible (using, for example @rochacbruno 's idea). SQL databases and elasticsearch expose a very different set of interfaces and constraints that heavy influence the way we model the objects. Thus, as architect, I feel the need to have strong control over the process. While, as developer, I'm glade to have a easy tool to integrate both.

If the intention is perform data migration, maybe, a python class (or function) should be a better option.

```python
from esengine import Document
from esengine.fields import StringField

# es model
MAPPING = {
    "index": "analyzed",
    "store": "yes",
    "analyzer": "my_awesome_analizer",
    "search_analyzer": 'another_analizer'
}

class EsDoc(Document):
    _index = 'myindex'
    _doctype = 'doc'
    id = StringField()
    anotherField = StringField(mapping=MAPPING)
```

```python
# data migration module
def sql_es_migration(sqlAchemyObj):
    # At this point we need to think on how to tranlate objects from a 
    # sql data model to a nosql data model. It depends on the context and the
    # use cases.
    doc = EsDoc(anotherField=sqlAchemyObj.field)
    ...
    doc.save()

def migration():
    # warning: some configurations are allowed only at index creation and
    # elasticsearch have few ways to charge model rather than re index all data
    EsDoc.put_mappint()
    sqlAchemyObjs = get_obj_from_sql()
    for obj in sqlAchemyObjs:
        sql_es_migration(obj)
```

What you think?

**Comment by rlam3** [comment]
@rochacbruno I was play around with this for a while and stumbled upon event listeners from sqlalchemy. This sorta kinda provides you with more control over what the index should be. But at the same time you can control if the index should include properties... I'm not sure about migration though. I'm still stuck on this... Ex.


```

class ORMMODEL(db.Model):
    title = db.String()

from odm_models import ODMMODEL_INDEX

def after_delete(mapper,connection,state):

    """
    After sqlalchemy CRUD
    """

    doc = ODMMODEL_INDEX.get(
        id=state.id,
    )

    doc.delete()

db.event.listen(ORMMODEL, 'after_delete', after_delete)

```
