### ISSUE TITLE
'unicode' problem with Python3

### ISSUE THREAD

**Issue by tiagorm** [seek-ai/esengine#32]
I was trying to use esengine with Python3 for a project but is raising the following exception during import:

```
from esengine import StringField

in /esengine/bases/field.py
7 class BaseField(object):
8       _type = unicode
9       _default = None
10     _default_mapping = {'type': 'string'}
NameError: name 'unicode' is not defined
```

I am using python 3.5 and esengine 0.0.18

**Comment by ederfmartins** [comment]
Currently, esengine work only on python 2. There is a port to python 3 (https://github.com/catholabs/esengine/pull/28), but the pull request do not pass in the tests. Maybe you could review this branch and merge it :)

**Comment by tiagorm** [comment]
I will do that @ederfmartins. Thank you

**Comment by ederfmartins** [comment]
Now esengine is fully compatible with python 3 :dagger:
