### ISSUE TITLE
ArrayField of DateFields

### ISSUE THREAD

**Issue by andryw** [seek-ai/esengine#33]
Hi.
There is a bug when using an ArrayField of DateFields. If the field is:

dates = ArrayField(DateField())

saving the value is ok. But get the document raises an exception because the class ArrayField don't implement the from_dict function from DateField. Instead, it uses the from_dict from BaseField class.
In other types this is ok, but in DateField an exception is raised because it tries to parse the value in this way:
datetime("2010-10-10") [line 84 from bases/field.py]

**Comment by rochacbruno** [comment]
@andryw the workaround is to use `DateField(multi=True)` example in tests: https://github.com/catholabs/esengine/blob/master/tests/test_fields.py#L24

**Comment by ederfmartins** [comment]
@andryw @rochacbruno I will fix this bug.
The problem is in ArrayField that do not delegate from_dict to the inner element class. This way ArrayField(DateField()) runs the default BaseField::from_dict instead of DateField::from_dict
